# Generated by Django 5.1.7 on 2025-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
